name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN used to authenticate to the current repository'
    required: true
    default: 'default value if applicable'
outputs:
  release-url:
    description: 'The URL of the GitHub release that was drafted'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: orange
  icon: tag